replicaCount: 2

image:
  repository: ghcr.io/nathansegers/fastapi-intro
  tag: v1.0.0

nameOverride: "rune-fastapi"
fullNameOverride: "rune-fastapi-demo"

serviceAccount:
  create: true
  name: helm-service-account

imagePullSecrets: []